### ISSUE TITLE
Add support for Google+

### ISSUE THREAD

**Issue by Vernal** [postmatic/social#15]

**Comment by filkaris** [comment]
![screenshot from 2015-09-19 17 45 26](https://cloud.githubusercontent.com/assets/1624978/9976757/52f66876-5ef6-11e5-85d6-a31ed9338403.png)

Permissions are ok

**Comment by Vernal** [comment]
Hey Filippos,

I just double-checked that settings screen you asked me to investigate in the google app console. No luck. There is nowhere to choose the app permissions....

**Comment by filkaris** [comment]
Good news :smiley:
