### ISSUE TITLE
Replace logo with cleaner version and link to Postmatic site

### ISSUE THREAD

**Issue by Vernal** [postmatic/social#2]

**Comment by filkaris** [comment]
@Vernal Please provide the link to the cleaner logo version. Thank you

**Comment by Vernal** [comment]
I assigned a few of these to myself. You can ignore them. I believe this is one.

**Comment by filkaris** [comment]
You're right, thanks!

Is there a live test site where I can see the other issues? (It takes long for me to set up individual apps for each API etc.)

**Comment by Vernal** [comment]
Let me know when you get the other networks in place and i'll set those up
as well.

On Sat, Sep 12, 2015 at 10:44 AM, Filippos Karailanidis <
notifications@github.com> wrote:

> You're right, thanks!
> 
> Is there a live test site where I can see the other issues? (It takes long
> for me to set up individual apps for each API etc.)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/social/issues/2#issuecomment-139778608.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059
