### ISSUE TITLE
WordPress 4.4 Comment Form Changes - Lost Comments

### ISSUE THREAD

**Issue by ronalfy** [postmatic/social#25]
If you start a comment, and click on social login, comment disappears and you have to re-type everything.

**Comment by Vernal** [comment]
Oh crap that's going to be a problem.

On Sun, Oct 25, 2015 at 5:21 PM, Ronald Huereca notifications@github.com
wrote:

> If you start a comment, and click on social login, comment disappears and
> you have to re-type everything.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/social/issues/25.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by ronalfy** [comment]
Should be fixed with https://github.com/postmatic/social/commit/0ef796c88f39079965ec77a232dff0f9527ef47b

Sorry for all the version bumping. I have some serious caching on MediaRon, so every time I update the script, I need to bump the version.
