### ISSUE TITLE
Ask for email address if/when using twitter

### ISSUE THREAD

**Issue by Vernal** [postmatic/social#27]
If the user is using Postmatic and signs in with Twitter we should ask them for an email address for followup comments. Could be difficult.

**Comment by DannyBrownCA** [comment]
Not sure if that would make sense. Adds hoops to jump through, and commenter probably using Twitter to comment as they don't want email?

**Comment by Vernal** [comment]
It'd only ask them if they check the box to subscribe by email.....

On Mon, Oct 26, 2015 at 3:30 PM, DannyBrownCA notifications@github.com
wrote:

> Not sure if that would make sense. Adds hoops to jump through, and
> commenter probably using Twitter to comment as they don't want email?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/social/issues/27#issuecomment-151258445.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by DannyBrownCA** [comment]
So they'd still see box if commenting via social? Or is that just Twitter?

**Comment by Vernal** [comment]
They would see the _subscribe via email_ box no matter what network they
use. We are able to scrape their email from all networks except for
Twitter.

In the case of Twitter, if they checked the box, we'd have to throw up a
prompt asking them what address they want to use... :(

On Mon, Oct 26, 2015 at 3:33 PM, DannyBrownCA notifications@github.com
wrote:

> So they'd still see box if commenting via social? Or is that just Twitter?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/social/issues/27#issuecomment-151259425.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by DannyBrownCA** [comment]
OK, that makes sense. Though wondering if the "scrape email addresses" would need a new disclosure policy, as well as upfront messaging and permissions to do so?

**Comment by Vernal** [comment]
It asks the user for the email address when they first link their social
account. It's clear at that step...

On Mon, Oct 26, 2015 at 3:38 PM, DannyBrownCA notifications@github.com
wrote:

> OK, that makes sense. Though wondering if the "scrape email addresses"
> would need a new disclosure policy, as well as upfront messaging and
> permissions to do so?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/social/issues/27#issuecomment-151260904.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by ronalfy** [comment]
I tried my best to get an e-mail address working, but the Twitter one always takes precedence. If I have more time, I'll give this another go.

**Comment by ronalfy** [comment]
Should be fixed / addressed here. https://github.com/postmatic/social/pull/36

**Comment by ronalfy** [comment]
Please close if your tests come back positive.
