### ISSUE TITLE
When authenticating with Google the app only asks for offline access. 

### ISSUE THREAD

**Issue by Vernal** [postmatic/social#4]
I’m not sure if this is because of how I have my google app configured or not. It could be my fault. Try it and see what you get. The result is that when authenticated with Google, WordPress still asks for name/email/url and does not show any indication that the authentication has occurred.

**Comment by filkaris** [comment]
It looks like you have to configure the app here as well. This is the error I'm getting:

"errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration.",
    "extendedHelp": "https://console.developers.google.com"
   }
  ],

**Comment by Vernal** [comment]
I can't figure this one out. I tried the original plugin and it throws the same problem. I think our authentication method is wrong and we are going to have to rewrite it.
