### ISSUE TITLE
Problem with email field when used without Postmatic

### ISSUE THREAD

**Issue by johnpuddephatt** [postmatic/social#49]
Having a problem with email values going astray when this plugin is used without Postmatic and a comment is left without connecting/linking to a social network. The problem doesn't occur with Postmatic is enabled.

Steps to reproduce:

• This plugin is installed with twitter login enabled (not tested with other networks)
• The wordpress discussion setting 'Users must be registered and logged in to comment' is unchecked
• A comment is added without using social login (i.e. just by filling out the name/email/website/comment fields)
• the email field clears when submit is clicked
• the value in the email field is not stored with the comment, and if the 'Comment author must fill out name and e-mail' discussion setting is checked then an error message is received

Can anyone confirm?

**Comment by johnpuddephatt** [comment]
Not sure if it's related but does anyone have any idea why the submitted email address is being stored in two different cookies? (or at least is when things are working – in the scenario above neither cookie is created!)

There's the wordress `comment_author_email_` one but there's also a `pms_comment_author_email_` one too...

**Comment by johnpuddephatt** [comment]
Ah ok, looks like the `pms_comment_author_email_` cookie is used for the postmatic email notifications input.  Confusingly (I think) it's being set even if I don't fill that field in...

**Comment by Vernal** [comment]
Hey John,

I'll try to take a look at that later today. I haven't heard mention of it otherwise. 

pms_comment_author_email is used in this case:
- The user signs in using twitter 
- Postmatic is installed
- If the user chooses to subscribe via email we then have to ask for an email address because we cannot get it from twitter
- That address is passed to pms_comment_author_email.

Amiright, @cyberhobo?

**Comment by erscampbell** [comment]
Is this the error you're referring to?

![email twitter error](https://cloud.githubusercontent.com/assets/13645981/11545648/5e930a40-9916-11e5-8499-cb961a72e89e.png)

Using the configuration in your post above, I now get this message every time I try to leave a comment without using social login.

**Comment by johnpuddephatt** [comment]
Yep that's the one, thanks for confirming!

It's a wordpress error – you can get rid of it by unchecking the 'Users must be registered and logged in to comment' setting in Discussion > Settings, but then comments are just saved without an email address.

**Comment by Vernal** [comment]
Yea, this isn't right. We'll get on it!

**Comment by cyberhobo** [comment]
Think I got it. We should put out 1.0.1 soon to fix this and #50.

**Comment by Vernal** [comment]
Awesome. Need to do a version bump as well. Let's try to push it by wed.
I've got a few other things to clean up on my end.

On Sun, Dec 6, 2015 at 8:18 PM, Dylan Kuhn notifications@github.com wrote:

> Think I got it. We should put out 1.0.1 soon to fix this and #50
> https://github.com/postmatic/postmatic-social/issues/50.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/postmatic-social/issues/49#issuecomment-162385011
> .

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059
