### ISSUE TITLE
Remove font-awesome? Increase icon size?

### ISSUE THREAD

**Issue by erscampbell** [postmatic/social#54]
Posted on behalf of [sixer](https://wordpress.org/support/topic/remove-font-awesome-increase-icon-size):

---

Great plugin thank you!

Is there a way to remove font-awesome from loading because my theme already loads it.

Also I would like to increase the size of the icons, how would I do that?

Thanks!

**Comment by Vernal** [comment]
@filkaris let's make an option to not load fontawesome in case it is already loaded.
