### ISSUE TITLE
postmatic-social-login.css is not loading

### ISSUE THREAD

**Issue by Vernal** [postmatic/social#61]
hey.. as of 1.1 the stylesheet isn't being loaded. not sure why. can you resolve and release asap?

**Comment by cyberhobo** [comment]
It lists postmatic-social-font-awesome as a dependency, but it looks that isn't always loaded anymore. I also don't see any fonts in the styles so I'll try just removing the dependency. It looks like we might not ever need to load font-awesome CSS, but I'll leave it in case I don't understand. @filkaris, feel free to chime in if I have anything wrong.

**Comment by Vernal** [comment]
The idea was to not load font-awesome if it was already present. Previous to 1.1 it loaded all the time. That is all I know.

**Comment by cyberhobo** [comment]
What motivated that? Are you certain it's even used?

**Comment by Vernal** [comment]
What motivated the change in 1.1 is that font-awesome would load even if it was already present in the active theme. It is used to generate the social icons...
